all:
  hosts:
    ca:
      ansible_host: 192.168.0.2
    dns:
      ansible_host: 192.168.0.3
    pve:
      ansible_host: 192.168.68.250
  children:
    ld_grp:
      hosts:
        ca:
        dns:
    pve_grp:
      hosts:
        pve: